### ISSUE TITLE
Page initialization exception

### ISSUE THREAD

**Issue by adersh-zmt** [zkoss/zk-angular#5]
Page initialization exception:: java.lang.NullPointerException
    at org.zkoss.zkmax.bind.impl.TrackerImplEx.getOrCreateTrackerNode(TrackerImplEx.java:137) [zkmax-8.0.0.jar:]
    at org.zkoss.zkmax.bind.impl.TrackerImplEx.addTracking(TrackerImplEx.java:76) [zkmax-8.0.0.jar:]
    at org.zkoss.bind.xel.zel.BindExpressionBuilder.addTracking(BindExpressionBuilder.java:116) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.xel.zel.BindExpressionBuilder.visitNode(BindExpressionBuilder.java:138) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.xel.zel.BindExpressionBuilder.visit(BindExpressionBuilder.java:57) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.zel.impl.parser.SimpleNode.accept(SimpleNode.java:141) [zel-8.0.0.jar:8.0.0]
    at org.zkoss.zel.impl.lang.ExpressionBuilder.prepare(ExpressionBuilder.java:150) [zel-8.0.0.jar:8.0.0]
    at org.zkoss.zel.impl.lang.ExpressionBuilder.build(ExpressionBuilder.java:168) [zel-8.0.0.jar:8.0.0]
    at org.zkoss.zel.impl.lang.ExpressionBuilder.createValueExpression(ExpressionBuilder.java:231) [zel-8.0.0.jar:8.0.0]
    at org.zkoss.zel.impl.ExpressionFactoryImpl.createValueExpression(ExpressionFactoryImpl.java:66) [zel-8.0.0.jar:8.0.0]
    at org.zkoss.bind.xel.BindXelFactory.parseExpression(BindXelFactory.java:30) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.impl.BindEvaluatorXImpl.parseExpressionX(BindEvaluatorXImpl.java:84) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.angular.AngularBinder$3.parseExpressionX(AngularBinder.java:163) [zk-angular-0.8.0.jar:]
    at org.zkoss.bind.impl.AccessInfo.create(AccessInfo.java:71) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.impl.PropertyBindingImpl.<init>(PropertyBindingImpl.java:67) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.impl.LoadPropertyBindingImpl.<init>(LoadPropertyBindingImpl.java:48) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.impl.BinderImpl.newLoadPropertyBinding(BinderImpl.java:946) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.impl.BinderImpl.addPropertyLoadBindings0(BinderImpl.java:1056) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.impl.BinderImpl.addPropertyLoadBindings(BinderImpl.java:797) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.angular.AngularBinder.addPropertyLoadBindings(AngularBinder.java:105) [zk-angular-0.8.0.jar:]
    at org.zkoss.bind.impl.AnnotateBinderHelper.processPropertyPromptBindings(AnnotateBinderHelper.java:362) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.impl.AnnotateBinderHelper.processPropertyBindings(AnnotateBinderHelper.java:246) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.impl.AnnotateBinderHelper.processComponentBindings0(AnnotateBinderHelper.java:124) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.impl.AnnotateBinderHelper.processAllComponentsBindings(AnnotateBinderHelper.java:89) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.impl.AnnotateBinderHelper.initComponentBindings(AnnotateBinderHelper.java:74) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.AnnotateBinder.initAnnotatedBindings(AnnotateBinder.java:73) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.bind.BindComposer.doAfterCompose(BindComposer.java:177) [zkbind-8.0.0.jar:8.0.0]
    at org.zkoss.angular.AngularComposer.doAfterCompose(AngularComposer.java:71) [zk-angular-0.8.0.jar:]
    at org.zkoss.zk.ui.impl.UiEngineImpl.doAfterCompose(UiEngineImpl.java:588) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.impl.UiEngineImpl.execCreateChild0(UiEngineImpl.java:931) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.impl.UiEngineImpl.execCreateChild(UiEngineImpl.java:877) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.impl.UiEngineImpl.execCreate0(UiEngineImpl.java:748) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.impl.UiEngineImpl.execCreate(UiEngineImpl.java:709) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.impl.UiEngineImpl.execCreateChild0(UiEngineImpl.java:923) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.impl.UiEngineImpl.execCreateChild(UiEngineImpl.java:877) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.impl.UiEngineImpl.execCreate0(UiEngineImpl.java:748) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.impl.UiEngineImpl.execCreate(UiEngineImpl.java:709) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.impl.UiEngineImpl.execNewPage0(UiEngineImpl.java:452) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.impl.UiEngineImpl.execNewPage(UiEngineImpl.java:358) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.http.DHtmlLayoutServlet.process(DHtmlLayoutServlet.java:217) [zk-8.0.0.jar:8.0.0]
    at org.zkoss.zk.ui.http.DHtmlLayoutServlet.doGet(DHtmlLayoutServlet.java:136) [zk-8.0.0.jar:8.0.0]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:734) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1187) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at com.juump.console.web.CharsetFilter.doFilter(CharsetFilter.java:38) [classes:]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:389) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]

**Comment by jumperchen** [comment]
do you have any example to reproduce this issue?

**Comment by adershzinemind** [comment]
Used the simple example in my project for testing that time this error occurred.

**Comment by adershzinemind** [comment]
Uncaught TypeError: Cannot read property 'apply' of undefined
 error when i added this <script src="/js/angular/app.js"></script> inside the body tag

**Comment by adershzinemind** [comment]
The problem is occurred in 8.0.0 working file in zk version 8.0.1 when will you release the 8.0.1 version

**Comment by jumperchen** [comment]
Good to hear that, we will arrange a ZK 8.0.1 release soon.
